### ISSUE TITLE
problems with nta/numenta-apps/htmengine$ python setup.py develop --user

### ISSUE THREAD

**Issue by mbernet4** [nupic-community/htmengine-traffic-tutorial#11]
I have successfully installed nupic and run both one_gym tutorials.  Now trying to do the traffic tutorial.
I believe I have performed all the prerequisites of https://github.com/htm-community/skeleton-htmengine-app up to step 2.
I get the numenta-apps while in the nta folder as follows:
git clone https://github.com/numenta/numenta-apps.git   

Start have problems with the following:

```
gbsd@ubuntu:~/nta/numenta-apps/htmengine$ python setup.py develop --user
running develop
running egg_info
creating htmengine.egg-info
writing requirements to htmengine.egg-info/requires.txt
writing htmengine.egg-info/PKG-INFO
writing top-level names to htmengine.egg-info/top_level.txt
writing dependency_links to htmengine.egg-info/dependency_links.txt
writing manifest file 'htmengine.egg-info/SOURCES.txt'
reading manifest file 'htmengine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.csv' under directory 'htmengine'
writing manifest file 'htmengine.egg-info/SOURCES.txt'
running build_ext
Creating /home/gbsd/.local/lib/python2.7/site-packages/htmengine.egg-link (link to .)
Adding htmengine 0.0.0 to easy-install.pth file

Installed /home/gbsd/nta/numenta-apps/htmengine
Processing dependencies for htmengine==0.0.0
Searching for nta.utils>=0.0.0
Reading https://pypi.python.org/simple/nta.utils/
Couldn't find index page for 'nta.utils' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for nta.utils>=0.0.0
error: Could not find suitable distribution for Requirement.parse('nta.utils>=0.0.0')
gbsd@ubuntu:~/nta/numenta-apps/htmengine$ 
```

Look like there is an issue with nta.utils,  below is a list of the main folder of nta.utils 

```
gbsd@ubuntu:~/nta/numenta-apps$ cd nta.utils
gbsd@ubuntu:~/nta/numenta-apps/nta.utils$ ll
total 84
drwxrwxr-x  5 gbsd gbsd  4096 May 31 15:11 ./
drwxrwxr-x 16 gbsd gbsd  4096 May 31 15:11 ../
drwxrwxr-x  2 gbsd gbsd  4096 May 31 15:11 conf/
-rw-rw-r--  1 gbsd gbsd  1015 May 31 15:11 DEPENDENCIES.md
-rw-rw-r--  1 gbsd gbsd    13 May 31 15:11 .gitignore
-rw-rw-r--  1 gbsd gbsd 34519 May 31 15:11 LICENSE.txt
-rw-rw-r--  1 gbsd gbsd    87 May 31 15:11 MANIFEST.in
drwxrwxr-x  3 gbsd gbsd  4096 May 31 15:11 nta/
-rw-rw-r--  1 gbsd gbsd    27 May 31 15:11 pytest.ini
-rw-rw-r--  1 gbsd gbsd  1876 May 31 15:11 README.md
-rw-rw-r--  1 gbsd gbsd   176 May 31 15:11 requirements.txt
-rw-rw-r--  1 gbsd gbsd  1368 May 31 15:11 setup.py
drwxrwxr-x  4 gbsd gbsd  4096 May 31 15:11 tests/
gbsd@ubuntu:~/nta/numenta-apps/nta.utils$ 
```

Add ideas what I am doing wrong?

**Comment by rhyolight** [comment]
@oxtopus Do you know if the `nta.utils` installation process has changed recently? We may need to update our docs.

**Comment by oxtopus** [comment]
No change. You _must_ manually install it _before_ `htmengine`.  We're not publishing `nta.utils` distributions to pypi, nor are we implementing versioning so you can't rely on `setuptools` to resolve dependencies on `nta.utils` or `htmengine`.  Please refer to the [README](https://github.com/numenta/numenta-apps/tree/master/htmengine#installation) in which it states:

> First, install nta.utils.

The process is the same as for `htmengine`:

```
cd nta.utils
python setup.py develop --user
```

**Comment by rhyolight** [comment]
@mbernet4 This is probably just an installation issue, not a bug. If you want to discuss further, why don't you join our forum and post your questions here: https://discourse.numenta.org/c/nupic.

**Comment by mbernet4** [comment]
FYI, I tried
cd nta.utils
python setup.py develop --user
As recommend above
and got and error  "EnvironmentError: mysql_config not found"
I then ran
sudo apt-get install libmysqlclient-dev
then i could run
python setup.py develop --user
in nta.utils folder and then in htmengine

Thanks all for the feedback, hope the above helps anyone else who runs into the same issue

Will also join https://discourse.numenta.org/c/nupic. as recommended
